(* 03.BNF - A simple set of productions with some alternatives and parentheses *)

Child     = FirstName Surname .
FirstName = ( "Helen" "Margaret" "Alice" ) | ( "Kenneth" "David" ) .
Surname   = "Terry" .
