(* 14.BNF - A simple set of productions with some alternatives
   and null productions *)

Lecturer  = FirstName Surname Degrees.
FirstName = ( "Dr" | "Professor" | "Mr" |   ) ( "P.D." | "Pat") .
Surname   = "Terry" .
Degrees   = "PhD" |   .
